#!/bin/bash
#
# Deploy a new version of guttormsgaardsarkiv.no
# Generated by Chef, your changes will perish

set -e

source ../deps/bin/activate

echo
echo "Deploying guttormsgaardsarkiv.no"
echo

pip install -r requirements.txt

echo "* Compiling locale files..."
for module in `find . -mindepth 2 -maxdepth 2 -type d -name locale -printf "%h\n"`
do
    echo "* Compiling locale files in $module..."
    cd $module
    django-admin.py compilemessages
    cd ..
done
echo "* Done compiling locale files."

echo "* Collecting static files..."
yes yes | ./manage.py collectstatic
echo "* Done collecting static files."

echo "* Migrating database..."
./manage.py syncdb --noinput --no-initial-data --migrate --traceback
echo "* Done migrating database."

echo
echo "guttormsgaardsarkiv.no has been deployed."
echo
