# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Built from https://github.com/dotzero/vagrant-debian-wheezy-64
    config.vm.box = "debian-wheezy-64"
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.provision "shell", inline: "curl -L https://www.opscode.com/chef/install.sh | sudo bash"

    config.vm.provision "chef_client" do |chef|
        chef.chef_server_url = "https://chef.incendio.no/"
        chef.validation_key_path = "chef-validator.pem"
        chef.add_recipe "host-guttorm"
    end

end
